### ISSUE TITLE
Error: Could not find or load main class hudson.remoting.jnlp.Main

### ISSUE THREAD

**Issue by damianmadeira** [jenkinsci/docker-inbound-agent#123]
Al querer iniciar un pod con una imagen generada a base de Rhel7-jenkins-slave en los eventos de Openshift aparece el error de asunto.
Le paso a alguno?
Lo único raro que veo en la descripción del pod es que en el template de containers jnlp el montado del serviceaccount en ves de usar un token especifico usa uno default, saben como se cambia para probar?

**Comment by slide** [comment]
Here's a rough translation from google translate

```
When you want to start a pod with an image generated from Rhel7-jenkins-slave in Openshift events, the subject error appears.
Did it happen to anyone?
The only rare thing I see in the description of the pod is that in the jnlp container template the serviceaccount assembly instead of using a specific token uses a default one, do you know how to change it to test?
```

**Comment by dduportal** [comment]
Closing as the RHEL 7 is not supported anymore
