### ISSUE TITLE
Jenkins agent does not return the success/failed exit code 

### ISSUE THREAD

**Issue by dluong777** [jenkinsci/docker-inbound-agent#128]
Basically I have a Jenkins master server to provision a bunch of Jenkins jobs to Jenkins Slaves nodes (AWS EC2 instances). Most of jobs are executed and finished successfully when looking at the Jenkins Console Logs. However, when **ssh-ing** into the EC2 instance and tried to `docker inspect` the exited container via `docker ps -aq -f status=exited | xargs docker inspects --format {{.State}}`, i found that most of the assumed `successful` jobs were exited with the `exited code=143`.  First doubting it was the Out of Memory based on the exit code, but inspect each container, the  `"OOMKilled": false` so i guess it was something else.  So i came to check the `docker logs` for that container 
```
Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
Dec 02, 2019 3:29:18 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: xxx
Dec 02, 2019 3:29:18 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Dec 02, 2019 3:29:19 PM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 3.20
Dec 02, 2019 3:29:19 PM hudson.remoting.Engine startEngine
WARNING: No Working Directory. Using the legacy JAR Cache location: /root/.jenkins/cache/jars
Dec 02, 2019 3:29:19 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among xxx
Dec 02, 2019 3:29:19 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
Dec 02, 2019 3:29:19 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: xxx
  Agent port:    44573
  Identity:     xxx
Dec 02, 2019 3:29:19 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Dec 02, 2019 3:29:19 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to xxx
Dec 02, 2019 3:29:19 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP4-connect
Dec 02, 2019 3:29:19 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Remote identity confirmed: xxx
Dec 02, 2019 3:29:20 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connected
Dec 02, 2019 3:30:14 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Terminated
```
then found no issue here.
So the only last place that came to my mind is that the entrypoint which i was using for Docker container (https://github.com/jenkinsci/docker-jnlp-slave/blob/master/jenkins-agent ) look like does not return the proper exit code after running.

**Comment by dduportal** [comment]
Hi @dluong777 do you still have the issue? If yes, can you provide more information about your setup so we could reproduce?

**Comment by dluong777** [comment]
@dduportal  Currently I have not got access to the environment/ test setup anymore so I cannot provide further information for you btw. IMHO, we can close this issue.
