### ISSUE TITLE
jnlp-agent:latest-windows - password for this account has expired

### ISSUE THREAD

**Issue by chrismathis** [jenkinsci/docker-inbound-agent#152]
When trying to launch a container from jnlp-agent:latest-windows I get an error:

ContainerCannotRun: container #### encountered an error during CreateProcess: failure in a Windows system call: The password for this account has expired. (0x532) extra info: {"CommandLine":"powershell.exe -f C:/ProgramData/Jenkins/jenkins-agent.ps1","User":"jenkins","WorkingDirectory":"c ....

It seems like the password for the jenkins account inside the container has expired.

This is probably related to the discussion here:
https://github.com/jenkinsci/docker-slave/issues/85#issuecomment-535033838

**Comment by wsj0000** [comment]
same issues on jnlp-agent:latest-windows-jdk11

**Comment by slide** [comment]
This should be fixed in the latest images. Please retest.

**Comment by chrismathis** [comment]
Yes, works for me with the latest image.

**Comment by romanolux** [comment]
As of now the error came up again since this night with the latest inbound-agent image released.   
![image](https://user-images.githubusercontent.com/11974715/86925394-21a15180-c131-11ea-92bd-59d3e009543f.png)

**Comment by nexaddo** [comment]
I just started seeing the same behavior about an hour or two ago as well.

**Comment by ssallmen** [comment]
The same issue came up for me. Last time ran (successfully) the container on July 6 and now it seems to fail. I am using jenkins/inbound-agent:jdk8-nanoserver-1809 image.

**Comment by allout58** [comment]
Can we reopen this, or get some details on how to fix this? Getting this 6 months later...

**Comment by slide** [comment]
Are you using the correct image? What docker image are you using? We have a test in place to make sure this isn't happening, so please make sure you are using the correct image.

**Comment by allout58** [comment]
I'm using `jenkins/inbound-agent:nanoserver-1809` and extending it. I just pulled yesterday, it was working, then had to make a change to my extension and rebuild and got this today.

**Comment by larsskj** [comment]
Yep - I'm hit as well.

**Comment by slide** [comment]
The issue would actually be in the jenkinsci/docker-agent image, not this one, as that is the base image for this image.

**Comment by slide** [comment]
Actually, what it looks like happened is an older tag was built and published which had this issue. I have kicked off a build to publish correct images again.

**Comment by larsskj** [comment]
The new build worked fine for me. Thank you!

**Comment by slide** [comment]
I disabled building older tags on CI, so hopefully this shouldn't happen again.

**Comment by fabiang** [comment]
Just had this today again with `windowsservercore-1809`. Upgrading to LTSC2019 helped.

**Comment by tpbrown** [comment]
> Just had this today again with `windowsservercore-1809`. Upgrading to LTSC2019 helped.

Ditto.  Thanks for posting.  Doing the same now too.
