### ISSUE TITLE
How to configure ssh keys for Jenkins Docker Slave & GitHub

### ISSUE THREAD

**Issue by Tea7ime** [jenkinsci/docker-inbound-agent#156]
Is there a recommended process for configuring keys on the jenkins docker slave? 

I'm attempting to use the clone recursive option to grab a submodule in a private GitHub repo. It appears that Jenkins is not using https credentials for this and instead, trying to use ssh. 

"git submodule update --init --recursive"....

Host key verification failed.
fatal: Could not read from remote repository.

**Comment by MarkEWaite** [comment]
Usually the preferred solution with git submodules is to list the submodule URL in the same protocol as the parent URL.  If the parent is cloned with https, then the submodule URL should use https.  If the parent is cloned with ssh, then the submodule URL should use ssh.  In that case, there is a setting in the git plugin which allows the credentials of the parent repository to be applied to all the submodules of that parent repository.

If that is not possible, then you could consider storing the credentials on the Jenkins docker agent before the clone happens.  For ssh, the credentials would need to be in the ~/.ssh directory of the user.  For https, you'll need to choose your credentials storage technique to be one that command line git supports.

**Comment by Tea7ime** [comment]
@MarkEWaite thanks for your help on this. Your response was very helpful!

It turns out that we had the url in .gitmodules for this submodule set for ssh which is what was keeping jenkins from using https automatically.

I configured the ssh key as a new password in Jenkins and configured the repo to be checkout with ssh through the gui.
