### ISSUE TITLE
Keep publishing official Debian Stretch images

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/docker-inbound-agent#168]
In [4.3-2](https://github.com/jenkinsci/docker-inbound-agent/releases/tag/4.3-2) we switched the default Linux versions from Stretch to Buster, but we still have Stretch Dockerfiles in our repos. Taking the feedback about package incompatibilities for other images, it would be great to keep shipping stretch

Suggested tags:

* `latest-stretch`
* `{version}-stretch`

Downstream of https://github.com/jenkinsci/docker-agent/issues/129

**Comment by dduportal** [comment]
Closing as Debian is currently using "bullseye" .
