### ISSUE TITLE
Windows and Linux should support the same parameters

### ISSUE THREAD

**Issue by carpnick** [jenkinsci/docker-inbound-agent#169]
If you dont do this, you get bugs like this [one](https://github.com/jenkinsci/amazon-ecs-plugin/issues/155) in higher level plugins.

Make the entrypoint consistent, and higher level plugins just work

Make Windows and Linux look like this one:
```
docker run --init jenkins/inbound-agent -url http://jenkins-server:port <secret> <agent name>
```

or this one:
```
docker run jenkins/inbound-agent:windowsservercore-1809 -Url http://jenkins-server:port -WorkDir=C:/Jenkins/agent -Secret <secret> -Name <agent name>
```

Be consistent.

**Comment by slide** [comment]
The Windows version was created that way to be more "windows-ish". I don't think we can change this at this point, since its already in-flight.

**Comment by carpnick** [comment]
So the expectation is then for all docker based plugins to implement the same conditional logic for windows/linux if they want to support both?  Seems like a missed opportunity to me.

**Comment by slide** [comment]
I agree it is not ideal.
