### ISSUE TITLE
Jnlp failing to connect to jenkins. user password expired ??

### ISSUE THREAD

**Issue by alsenydiallo** [jenkinsci/docker-inbound-agent#173]
`[Warning][default/elemental-windows-rel-122-8ktg5-vhqd7-j55lc][Failed] Error: failed to start container "jnlp": Error response from daemon: container jnlp encountered an error during CreateProcess: failure in a Windows system call: The password for this account has expired. (0x532) 

extra info: {"CommandLine":"powershell.exe -f C:/ProgramData/Jenkins/jenkins-agent.ps1","User":"jenkins","WorkingDirectory":"C:\\Users\\jenkins\\Jenkins","Environment":{"AGENT_WORKDIR":"C:/Users/jenkins/Jenkins/Agent","JAVA_BASE_URL":"https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u242-b08/OpenJDK8U-jdk_","JAVA_HOME":"C:\\openjdk-8","JAVA_URL_VERSION":"8u242b08","JAVA_VERSION":"8u242","JENKINS_AGENT_NAME":"elemental-windows-rel-122-8ktg5-vhqd7-j55lc","JENKINS_AGENT_WORKDIR":"/home/jenkins/agent","JENKINS_NAME":"elemental-windows-rel-122-8ktg5-vhqd7-j55lc","JENKINS_SECRET":"1a277354b27110896f45587809f9e096b99a3a2ba28b9026ddff677fb96cc2ab","JENKINS_SERVER_SERVICE_PORT":"tcp://10.100.101.107:80","JENKINS_SERVER_SERVICE_PORT_50000_TCP":"tcp://10.100.101.107:50000","JENKINS_SERVER_SERVICE_PORT_50000_TCP_ADDR":"10.100.101.107","JENKINS_SERVER_SERVICE_PORT_50000_TCP_PORT":"50000","JENKINS_SERVER_SERVICE_PORT_50000_TCP_PROTO":"tcp","JENKINS_SERVER_SERVICE_PORT_80_TCP":"tcp://10.100.101.107:80","JENKINS_SERVER_SERVICE_PORT_80_TCP_ADDR":"10.100.101.107","JENKINS_SERVER_SERVICE_PORT_80_TCP_PORT":"80","JENKINS_SERVER_SERVICE_PORT_80_TCP_PROTO":"tcp","JENKINS_SERVER_SERVICE_SERVICE_HOST":"10.100.101.107","JENKINS_SERVER_SERVICE_SERVICE_PORT":"80","JENKINS_SERVER_SERVICE_SERVICE_PORT_JENKINS_HTTP_SERVER":"80","JENKINS_SERVER_SERVICE_SERVICE_PORT_JENKINS_JNLP_AGENT":"50000","JENKINS_TUNNEL":"112.19.215.115:31210","JENKINS_URL":"http://112.19.215.115:31118/","KUBERNETES_PORT":"tcp://10.100.0.1:443","KUBERNETES_PORT_443_TCP":"tcp://10.100.0.1:443","KUBERNETES_PORT_443_TCP_ADDR":"10.100.0.1","KUBERNETES_PORT_443_TCP_PORT":"443","KUBERNETES_PORT_443_TCP_PROTO":"tcp","KUBERNETES_SERVICE_HOST":"10.100.0.1","KUBERNETES_SERVICE_PORT":"443","KUBERNETES_SERVICE_PORT_HTTPS":"443"},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[0,0]}`

**Comment by daevski** [comment]
Yeah... same here. I was hoping there was a command to reset it, but I've not found anything. And it looks like [this was fixed over here](https://github.com/jenkinsci/docker-agent/issues/111), but maybe not included in this repo yet?? Super frustrating...

**Comment by OrangeTimes** [comment]
Waiting for the fix

**Comment by slide** [comment]
The fix should be included already.

**Comment by alsenydiallo** [comment]
I found a way to bypass the issue. I looked into the dockerfile for the agent and created one for my project and rebuilder the image locally. After that everything worked fine. It almost feels like pulling the image from the official registry isn’t stable

**Comment by alsenydiallo** [comment]
I am more than happy to share the dockerfile on here is anyone needs it

**Comment by slide** [comment]
These images are new, they have some testing in place, but there are probably bugs. Feel free to open a PR or provide your solution.

**Comment by OrangeTimes** [comment]
The image on the docker hub was updated log time ago(Last updated 2 months ago by jenkinsinfraadmin). Probably fix is the code but nobody pushed the new docker image to registry itself? 
https://hub.docker.com/r/jenkins/jnlp-agent/tags

**Comment by slide** [comment]
jnlp-agent is not built from this repo. This image is pushed to https://hub.docker.com/r/jenkins/inbound-agent/tags. The jnlp-agent image is a separate image from here https://github.com/jenkinsci/jnlp-agents

**Comment by alsenydiallo** [comment]
What I really think is happening here is confusion with tags and naming. I recommend pulling the image from jenkins/inbound-agent:windowsservercore-1809.

**Comment by slide** [comment]
Yes, that is the best idea.

**Comment by jtnord** [comment]
the code used to add the user does not mark the password as non-expiring.  It marks the *account* as non expiring.

need to call `wmic useraccount WHERE Name='jenkins' set PasswordExpires=false` afterwards to prevent the password expiring after 60 days (or whatever the default is.

**Comment by jtnord** [comment]
NB: as per https://github.com/jenkinsci/docker-inbound-agent/pull/181#issuecomment-654587710 this is not fixed on the nanoserver based images.

**Comment by tynril** [comment]
This still happens on [this image](https://hub.docker.com/layers/jenkins/inbound-agent/windowsservercore-1809/images/sha256-1dfcabfb59d6c5453598a94763c367df5c206888c68150bdfce65b2da9cea516?context=explore), despite it using the `wmic` call.

That means there's currently no image without an expired password available.

**Comment by slide** [comment]
inbound-agent won't call that code at all because the jenkins user already exists. The fix needs to be upstream in the jenkinsci/docker-agent repo. I am looking into it.

**Comment by oleg-nenashev** [comment]
> inbound-agent won't call that code at all because the jenkins user already exists. The fix needs to be upstream in the jenkinsci/docker-agent repo. I am looking into it.

I will do it @slide

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/docker-inbound-agent/releases/tag/4.3-7 was released.

**Comment by alsenydiallo** [comment]
Great 👍, thanks to everyone for the active participation on getting this issue resolved

**Comment by zffocussss** [comment]
what is JENKINS_SECRET? how is it generated?
