### ISSUE TITLE
Pod gets created and terminated immediately with the following error

### ISSUE THREAD

**Issue by jayabalan1992** [jenkinsci/docker-inbound-agent#179]
I am using Kubernetes plugin version -1.19.3
Docker image - Inbound agent

I could connect to K8s cluster successfully. As soon as the job is scheduled, pod gets created and status change to Error and terminating. Below are the docker logs.

 i didn't change the default workdir - /home/jenkins/agent
No special settings in the K8s plugin config

Jenkins master running on On-Prem and k8s cluster on a separate VM

#docker logs 02f8aab4a728
Jun 20, 2020 8:15:47 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: inbound-agent-l6pkk
Jun 20, 2020 8:15:47 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Jun 20, 2020 8:15:47 PM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 4.3
Exception in thread "main" java.io.IOException: **The specified working directory should be fully accessible to the remoting executable (RWX): /home/jenkins/agent**
	at org.jenkinsci.remoting.engine.WorkDirManager.verifyDirectory(WorkDirManager.java:249)
	at org.jenkinsci.remoting.engine.WorkDirManager.initializeWorkDir(WorkDirManager.java:201)
	at hudson.remoting.Engine.startEngine(Engine.java:288)
	at hudson.remoting.Engine.startEngine(Engine.java:264)
	at hudson.remoting.jnlp.Main.main(Main.java:284)
	at hudson.remoting.jnlp.Main._main(Main.java:279)
	at hudson.remoting.jnlp.Main.main(Main.java:231)

**Comment by markyjackson-taulia** [comment]
This sounds to me like the Kubernetes cluster cannot converse with Jenkins. Is the Jenkins control plane within the Kubernetes cluster? If so, are you sure that the url/ip is correct in the Kubernetes cloud config in the Kubernetes plugin?

**Comment by jayabalan1992** [comment]
Yes, I verified the IP/Url in the kubernetes cloud config. Everything seems to be good. For some reason, I am seeing this error `_**Exception in thread "main" java.io.IOException: The specified working directory should be fully accessible to the remoting executable (RWX): /home/jenkins/agent` '**_

I am trying to understand what is remoting executable here. My assumption is this: When the jenkins master schedule a job in a container, it doesn't have right permission to access /home/jenkins/agent to create a workspace dir.


Some K8s output:

```
# kubectl get po -n jenkinsdocker
NAME                  READY   STATUS        RESTARTS   AGE
inbound-agent-vf4k0   1/2     Terminating   0          24s
inbound-agent-zr33p   0/2     Terminating   0          44s
```

As you can see, the status changed to error in 10 s and started terminating




```
  jnlp:
    Container ID:   docker://78d59e116a552d038278305d841749c719625160b0004e80e3e7f9372038120b
    Image:          jenkins/jnlp-slave:alpine
    Image ID:       docker-pullable://jenkins/jnlp-slave@sha256:d1bae9ca7174cb3570dc953400b284f9dd39afe410d24b22c3fd9c2bbf47ee26
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 20 Jun 2020 16:12:26 -0400
      Finished:     Sat, 20 Jun 2020 16:12:27 -0400
    Ready:          False
    Restart Count:  0
    Environment:
      JENKINS_SECRET:         7708b8bcfcb8af52ae3********edadaf69d15835f49fc2
      JENKINS_TUNNEL:         10.*.*.*:52001
      JENKINS_AGENT_NAME:     inbound-agent-h6g53
      JENKINS_NAME:           inbound-agent-h6g53
      JENKINS_AGENT_WORKDIR:  /home/jenkins/agent
      JENKINS_URL:            https://****.com/
```

**Comment by caseyduquettesc** [comment]
I also ran into this issue when I had a workspace volume that was dynamically allocated. In my case the error was caused by a permissions issue and I resolved it by enabling "Raw yaml for the pod"

```
apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
```

**Comment by abhishekkarigar** [comment]
Guys,   
Anyone found the solution?  
i am still facing this kind of issue when i am trying to create pods jenkins ( which is outside minikube cluster ) on windows

**Comment by HeshamZwayyed22** [comment]
> Guys,
> Anyone found the solution?
> i am still facing this kind of issue when i am trying to create pods from jenkinsci k8 plugin ( which is outside minikube cluster ) on windows
> 
> SEVERE: Failed to connect to http://127.0.0.1:8080/tcpSlaveAgentListener/: Connection refused (Connection refused)
> java.io.IOException: Failed to connect to http://127.0.0.1:8080/tcpSlaveAgentListener/: Connection refused (Connection refused)
> 
> AFAIK, the connection to jenkins master is happening from inbound docker container, which it will not find ( because theres no way for a container to talk to process running on host machine .)
> 
> can anybody tell what should be the value of **Jenkins Tunnel** ? right now i left it blank

Hi @abhishekkarigar ,

I have the same problem of connection refused to the jenkins URL, did you find the solution please ?

**Comment by abhishekkarigar** [comment]
it works when i install via helm in minikube or in docker-desktop for windows  
$ helm install -n jenkins jenkins/jenkins --values <values.yaml>

https://gist.github.com/abhishekkarigar/c5b92e4e76630042f38d8bc58c610695 for values.yaml file  

this worked for me

**Comment by acanewby** [comment]
I can confirm this is still the case with:

Kubernetes 1.21.6
Kubernetes plugin 1.31.3 (which uses jenkins/inbound-agent:4.11-1-jdk11 under the hood)
Jenkins 2.319.2

The exception is thrown by this code in the `verifyDirectory()` method of https://github.com/jenkinsci/remoting/blob/master/src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java :

```
if (!dir.canWrite() || !dir.canRead() || !dir.canExecute()) {
                throw new IOException("The specified " + type + " should be fully accessible to the remoting executable (RWX): " + dir.getPath());
            }
```

`dir` is an instance of `java.io.File` representing the Jenkins workspace.  When launched as a Kubernetes slave agent pod, it is described by the injected environment variable `JENKINS_AGENT_WORKDIR` as `/home/jenkins/agent`.

So, basically, what is happening here is that one of the `canWrite()`, `canRead()` or `canExecute()` tests is failing, causing the exception to be thrown.

In my own testing, I can reproduce this error when provisioning the Kubernetes slave agent Pod with either `workspaceVolume dynamicPVC( ... )` or `persistentVolumeClaimWorkspaceVolume( ... )`.  The error does not occur when using the default (which creates and attaches an EmptyDir{} volume).

What is curious is that if I override the `jnlp` container entrypoint with something like `sleep 99d` to bypass the default `/usr/local/bin/jenkins-agent`, I can then attach to the container and verify that I can create and modify files in the `/home/jenkins/agent' directory, regardless of how the workspace is provisioned.

Also, regardless of how the Jenkins workspace is provisioned (EmptyDir, static PVC, dynamic PVC), the running user `jenkins` cannot modify the `/home/jenkins/agent' directory itself, so the environment seems to be identical in all three use cases.

So, the question is: Why do we see `IOException` when using

```kubernetes {
    workspaceVolume dynamicPVC( ...)
}
```

or

```kubernetes {
    workspaceVolume persistentVolumeClaimWorkspaceVolume( ...)
}
```

**Comment by ss22219** [comment]
I also, agent version: jenkins/inbound-agent:4.11-1-jdk1

**Comment by timja** [comment]
This isn't the right place for the discussion.

This repo is only for packaging of the docker images.

Most likely should be reported to the kubernetes plugin or post on https://community.jenkins.io or the users mailing list

**Comment by taras-klym** [comment]
> I can confirm this is still the case with:
> 
> Kubernetes 1.21.6 Kubernetes plugin 1.31.3 (which uses jenkins/inbound-agent:4.11-1-jdk11 under the hood) Jenkins 2.319.2
> 
> The exception is thrown by this code in the `verifyDirectory()` method of https://github.com/jenkinsci/remoting/blob/master/src/main/java/org/jenkinsci/remoting/engine/WorkDirManager.java :
> 
> ```
> if (!dir.canWrite() || !dir.canRead() || !dir.canExecute()) {
>                 throw new IOException("The specified " + type + " should be fully accessible to the remoting executable (RWX): " + dir.getPath());
>             }
> ```
> 
> `dir` is an instance of `java.io.File` representing the Jenkins workspace. When launched as a Kubernetes slave agent pod, it is described by the injected environment variable `JENKINS_AGENT_WORKDIR` as `/home/jenkins/agent`.
> 
> So, basically, what is happening here is that one of the `canWrite()`, `canRead()` or `canExecute()` tests is failing, causing the exception to be thrown.
> 
> In my own testing, I can reproduce this error when provisioning the Kubernetes slave agent Pod with either `workspaceVolume dynamicPVC( ... )` or `persistentVolumeClaimWorkspaceVolume( ... )`. The error does not occur when using the default (which creates and attaches an EmptyDir{} volume).
> 
> What is curious is that if I override the `jnlp` container entrypoint with something like `sleep 99d` to bypass the default `/usr/local/bin/jenkins-agent`, I can then attach to the container and verify that I can create and modify files in the `/home/jenkins/agent` directory, regardless of how the workspace is provisioned.
> 
> Also, regardless of how the Jenkins workspace is provisioned (EmptyDir, static PVC, dynamic PVC), the running user `jenkins` cannot modify the `/home/jenkins/agent` directory itself, so the environment seems to be identical in all three use cases.
> 
> So, the question is: Why do we see `IOException` when using
> 
> ```
> kubernetes {
>     workspaceVolume dynamicPVC( ...)
> }
> ```
> 
> or
> 
> ```
> kubernetes {
>     workspaceVolume persistentVolumeClaimWorkspaceVolume( ...)
> }
> ```

Hi. Having identical issues. Were you able to resolve it?
