### ISSUE TITLE
JNLP fails to connect to master when istio envoy-proxy is present 

### ISSUE THREAD

**Issue by 370672701** [jenkinsci/docker-inbound-agent#192]
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
INFO: Agent discovery successful
Agent address: jenkins.operations.svc.cluster.local
Agent port: 50000
INFO: Handshaking
INFO: Connecting to jenkins.operations.svc.cluster.local:50000
INFO: Trying protocol: JNLP4-connect
Apr 16, 2019 1:29:01 PM org.jenkinsci.remoting.protocol.impl.AckFilterLayer abort
WARNING: [JNLP4-connect connection to jenkins.operations.svc.cluster.local/10.19.251.169:50000] Incorrect acknowledgement sequence, expected 0x000341434b got 0x485454502f
INFO: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Connection closed before acknowledgement sent at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)....

Jenkins 2.235.5

I have also suffered this issue on Jenkins 2.235.5, I use the nginx for proxy, which protocol I should be set on nginx ?

**Comment by slide** [comment]
This doesn't sound like it is isolated to the docker image for the agent, so, please file an issue in the Jenkins Jira or ask on the mailing list: https://groups.google.com/forum/#!forum/jenkinsci-users
