### ISSUE TITLE
Jenkins agent error

### ISSUE THREAD

**Issue by shwetalishinde-tomtom** [jenkinsci/docker-inbound-agent#197]
Failed to find resource bundle
java.util.MissingResourceException: Can't find bundle for base name /hudson/win32errors, locale en_US

java.lang.NoClassDefFoundError: java/sql/Date

**Comment by oleg-nenashev** [comment]
It looks like a Java 11 compatibility issue somewhere. We need a full
stacktrace to troubleshoot it further

**Comment by slide** [comment]
No update from @shwetalishinde-tomtom for over two years
