### ISSUE TITLE
Missing gerrit repo tool

### ISSUE THREAD

**Issue by Spinus1** [jenkinsci/docker-inbound-agent#208]
docker-inbound-agent contains git command, but not **gerrit** **repo** tool  (https://gerrit.googlesource.com/git-repo/).
This tool is used to track multiples repositories, not only in Android, but in many projects based on **Yocto**

I think that that repo tool should be installed in docker-inbound-agent, so it'll be easier to use Jenkins repo plugin https://plugins.jenkins.io/repo/

Note: I cannot use my own build container Docker that is containing repo tool since bug https://issues.jenkins.io/browse/JENKINS-30600 doesn't let you to run repo (and git) command into build Docker, but just in agent container.

Thanks,
Alessio

**Comment by MarkEWaite** [comment]
As far as I understand it @Spinus1, you can define your own Docker image based on this image and place the tools you want inside that image.

If that doesn't meet your needs, you can use the `withCredentials` block to provide a username / password to the https git clone.

If you're using ssh protocol for your git clone, then the ssh-agent plugin should allow you to place a call to repo inside an `sh` step that is within an sshagent block.

**Comment by slide** [comment]
I agree with @MarkEWaite, I don't think we should add the gerrit tool to this image since you can just build an image on top of this one and gerrit is not as ubiquitous as git.
