### ISSUE TITLE
Unable to pull Docker image

### ISSUE THREAD

**Issue by Hello-Linux** [jenkinsci/docker-inbound-agent#211]
I use k8s and jenkins build job,and get the error is
```
Unable to pull Docker image "jenkins/jnlp-slave:4.0.1-1". Check if image tag name is spelled correctly.

```
![2020-11-19 13-29-27 的屏幕截图](https://user-images.githubusercontent.com/17851645/99625565-7fdd2a00-2a6b-11eb-9ccf-52214795eaba.png)

**Comment by dg424** [comment]
Hi,
Did you figure out what the problem was ?

**Comment by OldPeel** [comment]
help me
I have the same problem, but I don't know where to start

**Comment by dduportal** [comment]
@OldPeel you should switch to the [community forums](community.jenkins.io) to get broader help.

Think about sharing (in the forum) as most configuration element as posible to allow people helping you to reproduce the error and better understand it (if it's a bug, developers need to understand what it is exactly)

**Comment by OldPeel** [comment]
I'm not sure if this is a Jenkins configuration issue or an image issue. I changed to a homemade image and still have this problem

**Comment by OldPeel** [comment]
![image](https://user-images.githubusercontent.com/86137842/233784842-c910950b-ac6b-4a2c-b07b-c5eef9a6f03f.png)

**Comment by dduportal** [comment]
@OldPeel please use the community forums, commenting on a closed issue to ask for help  is not a good way to get help.

**Comment by OldPeel** [comment]
What topic should I seek help on

**Comment by dduportal** [comment]
@OldPeel you wrote in https://github.com/jenkinsci/docker-inbound-agent/issues/211#issuecomment-1518502884

> help me
> I have the same problem, but I don't know where to start

I'm helping you by telling you to ask the same question in community.jenkins.io (https://github.com/jenkinsci/docker-inbound-agent/issues/211#issuecomment-1518526737).
I'm also adding that you should share information about your setup if you want some help.


Please, stop commenting here and open a topic in the community forum.
