### ISSUE TITLE
$VERSION is not passed correctly to docker in inboundAgent.Tests.ps1

### ISSUE THREAD

**Issue by sebok** [jenkinsci/docker-inbound-agent#213]
Recently the docker-agent image had a new release 4.6-2
I wanted to rebuild docker-inbound-agent to use the latest docker-agent and the unittests have failed because they referred to 4.6-1

The dockerfiles refer to base images through ARG VERSION 
The tests/inboundAgent.Tests.ps1 wants to pass this arg to docker, but docker doesn't recognize it and always use the default from 
DockerFile.

The --build-arg **'**VERSION=$VERSION**'** should be --build-arg $VERSION=$VERSION (quotes removed)

**Comment by dduportal** [comment]
See See https://github.com/jenkinsci/docker-inbound-agent/issues/279 and https://github.com/jenkinsci/docker-inbound-agent/pull/280 .
