### ISSUE TITLE
bash: docker: command not found

### ISSUE THREAD

**Issue by xgy560501** [jenkinsci/docker-inbound-agent#215]
I can't use the docker command in the docker slave,however i mount the docker.sock file to pod.

**Comment by MarkEWaite** [comment]
The issue tracker for the jenkins.io documentation site is used to track issues with the Jenkins documentation.  Your request seems to be a request for help, not a report of a documentation issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.

The message `docker: command not found` likely indicates that the Docker CE command line interface is not installed in the docker inbound agent.  The Docker inbound agent by default does not install the Docker CE command line interface.  If you need it installed, you'll need to create your own image.

**Comment by HariSekhon** [comment]
@xgy560501 you can use an sub-image of this one with the `docker.io` deb package installed, like this one I rustled up quickly:

https://hub.docker.com/repository/docker/harisekhon/jenkins-agent-docker

Source is here:

https://github.com/HariSekhon/Dockerfiles/tree/master/jenkins-agent-docker
