### ISSUE TITLE
JDK8 release not updated using 8u275

### ISSUE THREAD

**Issue by Fixmetal** [jenkinsci/docker-inbound-agent#216]
Hello,
I've just stumbled on this since I'm still using JDK8 images.
It seems that jenkins-inbound-agent JDK8 image is using `8u272`, but OpenJDK has been updated to `8u275` since 2020/11/11.
Jenkins inbound agent image is based on `jenkins/agent` image which is based on `openjdk:8-jdk-buster` which is now based on 8u275. See relevant links below:

[Jenkins inbound agent jdk8 debian Dockerfile](https://github.com/jenkinsci/docker-inbound-agent/blob/master/8/debian/Dockerfile)
[Jenkins agent jdk 8 debian Dockerfile](https://github.com/jenkinsci/docker-agent/blob/master/8/buster/Dockerfile)
[OpenJDK 8 Dockerfile](https://github.com/docker-library/openjdk/commit/70b5e5f035002633169423e237cffb65c7a39d4f#diff-420b9c574ff3bcb0b3323d4e0336c9112a8f25c5033831ee0591cda47572a85f)

I guess the natural way would be to publish `jenkins/inbound-agent:4.6-2` since `jenkins/agent` has already reached that tag.

**Comment by Fixmetal** [comment]
Hello,
any updates on this?

**Comment by Fixmetal** [comment]
Hello,
I see now it's getting dramatic. Now we are at Java `8u292` on Debian 9 (oldstable):

https://github.com/docker-library/openjdk/commit/765a1c4dd6fa4fd9c2a0cf540e9c17ca73eb227b
https://packages.debian.org/stretch/openjdk-8-jdk-headless

but seems jenkins-inbount-agent `jdk8` image is only maintained for Windows based containers which get updates regularly (11 days ago as of today):

- https://hub.docker.com/layers/jenkins/inbound-agent/4.6-1-nanoserver-1809/images/sha256-8e1d1b5b94308762d574bb32d823b54cbc65d331fa5c9709fa0b676dc23f2a4e?context=explore

Linux based has been updated 6 months ago:

- https://hub.docker.com/layers/jenkins/inbound-agent/4.6-1/images/sha256-19b6cb12bffa7e0d108fd66b14df96c819f729dc4ab7e0a43d53cbe154899b53?context=explore

Is there any deprecation notice from Jenkins over JDK8 in the next feature? Why Windows agents are being maintained whilst Linux are not?

**Comment by MarkEWaite** [comment]
> Hello,
> I see now it's getting dramatic. Now we are at Java `8u292` on Debian 9 (oldstable):
> 
> [docker-library/openjdk@765a1c4](https://github.com/docker-library/openjdk/commit/765a1c4dd6fa4fd9c2a0cf540e9c17ca73eb227b)
> https://packages.debian.org/stretch/openjdk-8-jdk-headless
> 
> but seems jenkins-inbount-agent `jdk8` image is only maintained for Windows based containers which get updates regularly (11 days ago as of today):
> 
> * https://hub.docker.com/layers/jenkins/inbound-agent/4.6-1-nanoserver-1809/images/sha256-8e1d1b5b94308762d574bb32d823b54cbc65d331fa5c9709fa0b676dc23f2a4e?context=explore
> 
> Linux based has been updated 6 months ago:
> 
> * https://hub.docker.com/layers/jenkins/inbound-agent/4.6-1/images/sha256-19b6cb12bffa7e0d108fd66b14df96c819f729dc4ab7e0a43d53cbe154899b53?context=explore
> 
> Is there any deprecation notice from Jenkins over JDK8 in the next feature? Why Windows agents are being maintained whilst Linux are not?

No deprecation notice.  We're not deprecating JDK 8 support.  Windows agents are being updated because a contributor submitted a pull request that causes them to be updated more frequently.

Would you be interested in helping with Docker image maintenance?  We'd love to have additional contributors submit pull requests.  We've implemented [dependabot on the Jenkins controller images](https://github.com/jenkinsci/docker/blob/master/.github/dependabot.yml) and have made the transition from using the openjdk images to use adoptopenjdk images.  It would be great to make a similar transition in the agent images.

**Comment by Fixmetal** [comment]
> No deprecation notice. We're not deprecating JDK 8 support. Windows agents are being updated because a contributor submitted a pull request that causes them to be updated more frequently.
> 
> Would you be interested in helping with Docker image maintenance? We'd love to have additional contributors submit pull requests. We've implemented [dependabot on the Jenkins controller images](https://github.com/jenkinsci/docker/blob/master/.github/dependabot.yml) and have made the transition from using the openjdk images to use adoptopenjdk images. It would be great to make a similar transition in the agent images.

Thanks for the explanation. Sounds good, let me work that out and I will do a PR then.

**Comment by MarkEWaite** [comment]
Resolved for an extended period
