### ISSUE TITLE
Alpine jdk11 not published on DockerHub

### ISSUE THREAD

**Issue by Dorvaryn** [jenkinsci/docker-inbound-agent#221]
I noticed that the jdk11 version of the alpine image is not published to dockerhub (https://hub.docker.com/r/jenkins/inbound-agent/tags?page=1&ordering=last_updated&name=alpine).

I see there is a DockerFile for it already, is there any reason why it is not published ? I am currently using the alpine image and am migrating a few projects to jdk11 so would appreciate being able to use your image.

**Comment by fabiang** [comment]
Please see [Docker packaging for Alpine/Slim](https://github.com/jenkinsci/jep/tree/master/jep/211#docker-packaging-for-alpineslim). OpenJDK11 isn't available for Alpine and therefor jdk11-alpine images are based on [AdoptOpenJDK](https://adoptopenjdk.net), which as far as I can see is not fully supported.

To improve this situation, I guess you'll need to build those images by your own and report back problems as much as you can.

**Comment by MarkEWaite** [comment]
Alpine image for JDK 11 is available.
