### ISSUE TITLE
Feature Request: Add docker.io package for docker command

### ISSUE THREAD

**Issue by HariSekhon** [jenkinsci/docker-inbound-agent#222]
### Feature Request

Please add the `docker.io` package to provide the `docker` command as this is very common software for CI/CD and Jenkins build wrappers assume it's available if the pipeline specifies a docker agent, and fails otherwise like #215.

This is extremely commonly used for:

1.  consistent app builds
2. building your own Docker images as part of your CI/CD pipeline before deployment
3. if you need to run commands using Cloud SDK tools eg. `gcr.io/google.com/cloudsdktool/cloud-sdk`

Having to sub-Dockerfile this and maintain forked images is not really a good solution when this could just be baked in to the core image.

**Comment by HariSekhon** [comment]
For now I've quickly rustled up a derived image of inbound-agent with the `docker.io` deb package installed:

https://hub.docker.com/repository/docker/harisekhon/jenkins-agent-docker

Source is here on GitHub:

https://github.com/HariSekhon/Dockerfiles/tree/master/jenkins-agent-docker

**Comment by oleg-nenashev** [comment]
There is https://github.com/jenkinsci/jnlp-agents/tree/master/docker which could be slightly updated (e.g. adding another base image there). I do not think having Docker in the main image is a good idea, Docker executable is pretty heavy.

**Comment by HariSekhon** [comment]
I'm fine with it being in a different heavier image to not bloat the default inbound-agent image.

**Comment by oleg-nenashev** [comment]
Would you be interested to submit a pull request to the referenced repository? Thanks!

**Comment by HariSekhon** [comment]
It looks like that image is basically doing a similar thing to what I did, except that's using Alpine while I've stuck with the default stock image which is based on Debian.

I think the best way to solve this is to solve https://github.com/jenkinsci/docker-inbound-agent/issues/223, which would solve both issues, but require more thought.

**Comment by kirqe** [comment]
I wasted so much time trying to figure out why I couldn't run docker commands....

**Comment by dduportal** [comment]
Closing as per https://github.com/jenkinsci/docker-inbound-agent/issues/223#issuecomment-1712005925
