### ISSUE TITLE
arm64 docker image

### ISSUE THREAD

**Issue by morganchristiansson** [jenkinsci/docker-inbound-agent#228]
### Dependencies

Dockerfiles use `FROM jenkins/agent:$version`. Upstream image https://hub.docker.com/r/jenkins4eval/agent/tags has linux/amd64 but no linux/arm64.

### Feature Request

Add multi-arch support for amd64 and arm64 for inbound-agent image https://hub.docker.com/r/jenkins4eval/inbound-agent/tags

Same as #205 which was closed for requesting arm32. Requesting arm64 docker image.

**Comment by morganchristiansson** [comment]
I see jenkinsci/docker-agent#109 is open in upstream image

**Comment by qbixsd** [comment]
It's not open anymore ;-)

**Comment by timja** [comment]
because it's available

![image](https://user-images.githubusercontent.com/21194782/134471732-28eaf47b-2554-4c76-92bf-a278c5e619d8.png)

https://hub.docker.com/r/jenkins/inbound-agent/tags?page=1&ordering=last_updated&name=latest
