### ISSUE TITLE
[Question] what is JENKINS_SECRET for?

### ISSUE THREAD

**Issue by zffocussss** [jenkinsci/docker-inbound-agent#231]
Hi :
   Could someone help me what is JENKINS_SECRET for?how can it be generated and used?I planned to setup several agents in differrent platforms,such as k8s ,docker.

**Comment by MarkEWaite** [comment]
The issue tracker for the docker inbound agent  is used to track issues with the inbound agent.  Your request seems to be a request for help, not a report of an issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.  Many more people see questions there and that increasing the chance that you'll receive an answer.
