### ISSUE TITLE
Default locale encoding / charmap is ANSI_X3.4-1968

### ISSUE THREAD

**Issue by strangelookingnerd** [jenkinsci/docker-inbound-agent#238]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.308
OS: Windows 10 - 10.0
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Tried debian and alpine images - both behave the same for me.
```

### Reproduction steps

- Clean Jenkins install
- Configure Cloud & Agent Templates
- Configure Maven Tool to be used in Jobs
- Run simple Pipeline such as
```
pipeline {
    agent { 
        node('java-docker-agent')
    } 
    stages {
        stage('Build') {
            steps {
                withMaven(maven: 'MAVEN') {
                    sh "mvn -version"    
                }
            }
        }
    }
}
```

### Results

Expected result:
```
locale charmap
UTF-8
```

```
mvn -version
----- withMaven Wrapper script -----
Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/home/jenkins/workspace/test-pipeline@tmp/withMaven908d146e/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/home/jenkins/workspace/test-pipeline@tmp/withMaven908d146e" 
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/MAVEN
Java version: 11.0.12, vendor: Eclipse Foundation, runtime: /opt/java/openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-31-generic", arch: "amd64", family: "unix"
```

Actual result:
```
locale charmap
ANSI_X3.4-1968
```

```
mvn -version
----- withMaven Wrapper script -----
Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/home/jenkins/workspace/test-pipeline@tmp/withMaven908d146e/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/home/jenkins/workspace/test-pipeline@tmp/withMaven908d146e" 
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/MAVEN
Java version: 11.0.12, vendor: Eclipse Foundation, runtime: /opt/java/openjdk
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "5.11.0-31-generic", arch: "amd64", family: "unix"
```

### Additional Info
Maybe I'm totally wrong here but I sort of think that UTF-8 should be used. Is there any reason to use ANSI_X3.4-1968?
I know that I can set the default encoding for Maven via `MAVEN_OPTS=-Dfile.encoding=UTF-8` however I should not have to in the first place. This will likely affect other tools besides Maven as well. For me it produces hard to track issues further down the road e.g. in tests related to encoding of my Java application regarding creation of files and folder containing special characters.

**Comment by timja** [comment]
Probably need a similar fix to https://github.com/jenkinsci/docker/pull/1194

**Comment by timja** [comment]
This will be fixed by https://github.com/jenkinsci/docker-agent/pull/191, it will need a bump in
https://github.com/jenkinsci/docker-inbound-agent/blob/master/docker-bake.hcl#L26 once released

**Comment by strangelookingnerd** [comment]
@timja Thanks for the feedback. Will report back once the release is out.

**Comment by timja** [comment]
released now

**Comment by strangelookingnerd** [comment]
Works perfect, thanks again!
