### ISSUE TITLE
Windows tests are failing but build passes

### ISSUE THREAD

**Issue by timja** [jenkinsci/docker-inbound-agent#242]
### Version report

Jenkins and plugins versions report:

```
Copy/paste here....
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Paste here
```

### Reproduction steps

- Step 1...
- Step 2...

### Results

Expected result:

Actual result:

**Comment by slide** [comment]
Is there a log for the failures?

**Comment by timja** [comment]
e.g. https://ci.jenkins.io/blue/rest/organizations/jenkins/pipelines/Packaging/pipelines/docker-inbound-agent/branches/master/runs/174/nodes/9/log/?start=0

just check any windows build with the tests for this repo and they are failing
