### ISSUE TITLE
Upgrade to 4.11.2 - Jenkins inbound-agent latest version not working with latest LTS - 2.319.1

### ISSUE THREAD

**Issue by Hellspam** [jenkinsci/docker-inbound-agent#249]
### Version report

Jenkins: 2.319.1
OS: Linux - 4.14.35-1818.1.6.el7uek.x86_64
---
ace-editor:1.1
active-directory:2.25
ansible:1.1
ansible-tower:0.16.0
ansicolor:1.0.1
ant:1.13
antisamy-markup-formatter:2.5
apache-httpcomponents-client-4-api:4.5.13-1.0
artifactory:3.13.2
atlassian-bitbucket-server-integration:3.1.0
authentication-tokens:1.4
aws-credentials:1.32
aws-java-sdk:1.12.101-300.vc09c7be9cb57
aws-java-sdk-cloudformation:1.12.101-300.vc09c7be9cb57
aws-java-sdk-codebuild:1.12.101-300.vc09c7be9cb57
aws-java-sdk-ec2:1.12.101-300.vc09c7be9cb57
aws-java-sdk-ecr:1.12.101-300.vc09c7be9cb57
aws-java-sdk-ecs:1.12.101-300.vc09c7be9cb57
aws-java-sdk-elasticbeanstalk:1.12.101-300.vc09c7be9cb57
aws-java-sdk-iam:1.12.101-300.vc09c7be9cb57
aws-java-sdk-logs:1.12.101-300.vc09c7be9cb57
aws-java-sdk-minimal:1.12.101-300.vc09c7be9cb57
aws-java-sdk-ssm:1.12.101-300.vc09c7be9cb57
badge:1.9
basic-branch-build-strategies:1.3.2
blueocean:1.25.2
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.25.2
blueocean-commons:1.25.2
blueocean-config:1.25.2
blueocean-core-js:1.25.2
blueocean-dashboard:1.25.2
blueocean-display-url:2.4.1
blueocean-events:1.25.2
blueocean-git-pipeline:1.25.2
blueocean-github-pipeline:1.25.2
blueocean-i18n:1.25.2
blueocean-jira:1.25.2
blueocean-jwt:1.25.2
blueocean-personalization:1.25.2
blueocean-pipeline-api-impl:1.25.2
blueocean-pipeline-editor:1.25.2
blueocean-pipeline-scm-api:1.25.2
blueocean-rest:1.25.2
blueocean-rest-impl:1.25.2
blueocean-web:1.25.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-3
bouncycastle-api:2.25
branch-api:2.7.0
build-blocker-plugin:1.7.7
build-name-setter:2.2.0
build-timeout:1.20
build-timestamp:1.0.3
build-user-vars-plugin:1.8
built-on-column:1.1
caffeine-api:2.9.2-29.v717aac953ff3
categorized-view:1.12
checks-api:1.7.2
cloud-stats:0.27
cloudbees-bitbucket-branch-source:734.v2f848c5e6ea2
cloudbees-disk-usage-simple:0.10
cloudbees-folder:6.16
com.taboola.3rdpartylibs:1.0-SNAPSHOT (private-75fe5ac8-uri)
com.taboola.monitor:1.8.9-SNAPSHOT (private-5973d22f-builder)
command-launcher:1.6
compress-artifacts:1.10
compress-buildlog:1.2
conditional-buildstep:1.4.1
config-file-provider:3.8.2
configuration-as-code:1.55
configurationslicing:1.52
copyartifact:1.46.2
cors-filter:1.1
credentials:2.6.2
credentials-binding:1.27
dark-theme:155.v497c78bbdbb3
dashboard-view:2.18
data-tables-api:1.11.3-4
database:128.vaa83e142f7f2
database-mysql:1.4
description-setter:1.10
display-url-api:2.3.5
docker-commons:1.17
docker-workflow:1.26
downstream-ext:1.8
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-1
email-ext:2.85
extended-choice-parameter:0.82
extended-read-permission:3.2
extensible-choice-parameter:1.8.0
external-monitor-job:1.7
favorite:2.3.3
flexible-publish:0.16.1
font-awesome-api:5.15.4-3
git:4.10.0
git-client:3.10.0
git-parameter:0.9.13
git-server:1.10
git-userContent:1.4
github:1.34.1
github-api:1.301-378.v9807bd746da5
github-branch-source:2.11.3
google-metadata-plugin:0.3.1
google-oauth-plugin:1.0.6
google-storage-plugin:1.5.4.1
gradle:1.37.1
groovy:2.4
groovy-postbuild:2.5
h2-api:1.4.199
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.28
http_request:1.12
ivy:2.1
jackson2-api:2.13.0-230.v59243c64b0a5
javadoc:1.6
jaxb:2.3.0.1
jdk-tool:1.5
jenkins-design-language:1.25.2
jira:3.6
jjwt-api:0.11.2-9.c8b45b8bb173
job-dsl:1.78.1
job-import-plugin:3.4
job-restrictions:0.8
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
junit-attachments:1.7
kubernetes:1.30.11
kubernetes-client-api:5.4.1
kubernetes-credentials:0.9.0
ldap:2.7
leastload:3.0.0
lockable-resources:2.12
logstash:2.5.0205.vd05825ed46bd
mailer:1.34
material-theme:0.4.1
matrix-auth:2.6.8
matrix-project:1.19
maven-plugin:3.15.1
mercurial:2.16
metrics:4.0.2.8
metrics-graphite:3.0.0
momentjs:1.1.1
monitoring:1.88.0
nested-view:1.22
nodelabelparameter:1.10.1
oauth-credentials:0.5
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.6.1
parallel-test-executor:1.13
parameterized-scheduler:1.0
parameterized-trigger:2.42
permissive-script-security:0.7
pipeline-build-step:2.15
pipeline-github-lib:1.0
pipeline-graph-analysis:1.12
pipeline-input-step:2.12
pipeline-maven:3.10.0
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-multibranch-defaults:2.1
pipeline-rest-api:2.19
pipeline-stage-step:2.5
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.19
pipeline-utility-steps:2.11.0
plain-credentials:1.7
plugin-util-api:2.5.1
popper-api:1.16.1-2
popper2-api:2.10.2-1
postbuild-task:1.9
postbuildscript:3.0.0
prometheus:2.0.10
pubsub-light:1.16
rebuild:1.32
resource-disposer:0.16
rich-text-publisher-plugin:1.4
role-strategy:3.2.0
run-condition:1.5
run-condition-extras:0.3
saml:2.0.9
scm-api:2.6.5
script-security:1.78
sectioned-view:1.25
simple-theme-plugin:0.7
slack:2.49
snakeyaml-api:1.29.1
solarized-theme:0.1
sonar:2.14
sse-gateway:1.24
ssh-agent:1.23
ssh-credentials:1.19
ssh-slaves:1.33.0
sshd:3.1.0
structs:308.v852b473a2b8c
text-finder:1.17
theme-manager:0.6
throttle-concurrents:2.5
timestamper:1.15
token-macro:267.vcdaea6462991
trilead-api:1.0.13
uno-choice:2.5.7
variant:1.4
versioncolumn:2.2
windows-slaves:1.8
workflow-aggregator:2.6
workflow-api:2.47
workflow-basic-steps:2.24
workflow-cps:2640.v00e79c8113de
workflow-cps-global-lib:548.v9085a486966a
workflow-durable-task-step:1101.vf832bc1ac745
workflow-job:2.42
workflow-multibranch:2.26
workflow-scm-step:2.13
workflow-step-api:2.24
workflow-support:3.8
ws-cleanup:0.39

- What Operating System are you using (both controller, and any agents involved in the problem)?

Running Docker image configured with CasC on CentOS 7.2.1511

### Reproduction steps

- Configure K8S Plugin to use latest jenkins/inbound-agent image - tried latest, 4.11-1-jdk11 tags
- Configured with IdleMinutes to keep slave up
- First build succeeds on slave.
- Jenkins takes slave offline since remoting version does not match between master and slave

### Results

Expected result:

Slave is not taken offline

Actual result:

Slave is take offline due to version mismatch

**Comment by Hellspam** [comment]
![Screenshot 2021-12-05 173725](https://user-images.githubusercontent.com/915801/144753207-786ac237-fd96-484a-8002-5cd319faf687.png)

**Comment by MarkEWaite** [comment]
That usually means you've installed the [Versions Node Monitors plugin](https://plugins.jenkins.io/versioncolumn/) and are using its default configuration.  You'll need to adjust its configuration to accept a wider range of remoting versions.

![screencapture-mark-pc2-markwaite-net-8080-computer-configure-2021-12-05-09_05_09](https://user-images.githubusercontent.com/156685/144754235-c21c4340-2bfd-458d-b164-9226f904aa60.png)
