### ISSUE TITLE
Compatibility with Server versions

### ISSUE THREAD

**Issue by dg424** [jenkinsci/docker-inbound-agent#258]
### Describe your use-case which is not covered by existing documentation.

Looking for documentation that states which agent versions are compatible with which server versions.  For instance, we're currently trying to test 2.303.3 and wondering which agent is compatible with this release (or in the future which agent is compatible with any particular release) ?

**Comment by timja** [comment]
I don't think the doc exists, but generally we very rarely update the minimum remoting version required.

Unless you are having an issue, use a recent version with recent core.

**Comment by dg424** [comment]
Hi Tim,

Does the Java version have to match between the two ? I see that the project here has folders for 8, 11, and 17, so wondering if we can pick any version amongst those or pick the latest that corresponds to the Java version of the server we're using ? In our case, with 2.303.3, the server is Java 11, so does this mean the latest jdk11 tag here - https://hub.docker.com/layers/jenkins/inbound-agent/jdk11/images/sha256-f2f52f3e0346040947f72df2b0ac70d2d31f19489ff19d5af223f034a934b762?context=explore - is recommended since it's the most recent version ?

**Comment by timja** [comment]
You are recommended to use the same Java version between the server and the agent.

But it does _generally_ work even with mis-matches.

The recommended version is 11

**Comment by dg424** [comment]
So, just to clarify so that I can report this back to the team - For Java 11 server versions, the recommendation is to use the latest stable Java 11 inbound-agent version, which would be, according to Docker Hub - https://hub.docker.com/r/jenkins/inbound-agent/tags?page=1&name=jdk11, for linux/amd64, 4.11.2-4-jdk11 for the Debian image or 4.11.2-4-alpine-jdk11 for the Alpine image correct ?
Thanks so much for responding!

**Comment by timja** [comment]
yes

**Comment by dg424** [comment]
Thanks! Closing issue.
