### ISSUE TITLE
[Java 17] Image name is using the -preview" suffix despite official support for Java 17

### ISSUE THREAD

**Issue by gounthar** [jenkinsci/docker-inbound-agent#272]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

- latest (Debian Bullseye (11)?)
- Debian Bullseye (11)
- 4.10-3-jdk17 (Debian Bullseye (11)?)
- 4.11-1-jdk17 (Debian Bullseye (11)?)
- jdk17 (Debian Bullseye (11)?)
- 4.2.0 (Debian Bullseye (11)?)
- latest-alpine-jdk17
- alpine-jdk17
- 4.13.2-1-jdk17 (Debian Bullseye (11)?)
- 4.13.2-1-alpine-jdk17

### Reproduction steps

Open [Docker Hub](https://hub.docker.com/r/jenkins/inbound-agent/tags?page=1&name=jdk17) and confirm that most recent images do not have a `preview `suffix.
Three days ago, 4 of 4 produced images did have that suffix for JDK 17.

### Expected Results

No `preview `suffix.

### Actual Results

Includes the `preview `suffix.

**Comment by timja** [comment]
It's fine to remove but needs addressing in https://github.com/jenkinsci/docker-agent/blob/master/docker-bake.hcl first.

Would you like to send a PR?

**Comment by MarkEWaite** [comment]
> It's fine to remove but needs addressing in https://github.com/jenkinsci/docker-agent/blob/master/docker-bake.hcl first.
> 
> Would you like to send a PR?

@gounthar and I were hoping that we could persuade one of the interested new contributors to take on the set of issues related to JDK 17 container labels.  Those issues are:

* https://github.com/jenkinsci/docker-agent/issues/266
* https://github.com/jenkinsci/docker-ssh-agent/issues/137
* https://github.com/jenkinsci/docker-inbound-agent/issues/272

If no new contributor is willing to make the change within the next week or so, then we'll do it.
