### ISSUE TITLE
Docker image for 4.13.3

### ISSUE THREAD

**Issue by dg424** [jenkinsci/docker-inbound-agent#274]
### Jenkins and plugins versions report

Working on deployment the next release of Jenkins but need 4.13.3 agent as well.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

Look for 4.13.3 release on Docker Hub

### Expected Results

4.13.3 release on Docker Hub

### Actual Results

No such release on Docker Hub

### Anything else?

Hi,

Please see - https://issues.jenkins.io/browse/JENKINS-65873. There is an important OOM fix released, but there isn't a corresponding Docker image yet. Is it possible to release one matching this release ?

Thanks

**Comment by timja** [comment]
Begun with:

https://github.com/jenkinsci/docker-agent/releases/tag/4.13.3-1
https://github.com/jenkinsci/docker-agent/releases/tag/3046.v38db_38a_b_7a_86

There wasn't a GitHub release created of remoting 4.13.3-1 so I missed it (I've created it now).

**Comment by timja** [comment]
Published

**Comment by dg424** [comment]
> Published
> 
> 
> 
> ```
> 
> ➜  view-job-filters-plugin git:(refresh-plugin) reg tags jenkins/inbound-agent | grep 4.13.3
> 
> INFO[0000] domain: docker.io
> 
> INFO[0000] server address: https://registry-1.docker.io
> 
> 4.13.3-1
> 
> 4.13.3-1-alpine
> 
> 4.13.3-1-alpine-jdk11
> 
> 4.13.3-1-alpine-jdk17
> 
> 4.13.3-1-alpine-jdk8
> 
> 4.13.3-1-jdk11
> 
> 4.13.3-1-jdk11-nanoserver-1809
> 
> 4.13.3-1-jdk11-windowsservercore-ltsc2019
> 
> 4.13.3-1-jdk17
> 
> 4.13.3-1-jdk8
> 
> 4.13.3-1-jdk8-nanoserver-1809
> 
> 4.13.3-1-jdk8-windowsservercore-ltsc2019
> 
> 4.13.3-1-nanoserver-1809
> 
> 4.13.3-1-windowsservercore-ltsc2019
> 
> ```

Thanks Tim!
