### ISSUE TITLE
Inbound-agent image uses an old JDK and remoting

### ISSUE THREAD

**Issue by Vlatombe** [jenkinsci/docker-inbound-agent#279]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

MacOS12.6 / arm64

Same problem visible for amd64 images

### Reproduction steps

```
docker pull jenkins/inbound-agent:jdk11
docker run --rm jenkins/inbound-agent:jdk11 -version
docker run --entrypoint bash -ti jenkins/inbound-agent:jdk11
```
Then in the new container terminal
```
java -version
```

This returns

### Expected Results

```
3046.v38db_38a_b_7a_86-1-jdk11
jenkins@478c920572bd:~$ java -version
openjdk version "11.0.16.1" 2022-08-12
```

### Actual Results

```
4.10
jenkins@df409120a74f:~$ java -version
openjdk version "11.0.12" 2021-07-20
```

### Anything else?

* Rebuilding the image locally gives the expected result, so I believe this has to be some infrastructure caching issue.
* Running the `jenkins/inbound-agent:3046.v38db_38a_b_7a_86-1-jdk11` image generates the expected output.

**Comment by dduportal** [comment]
Status update: the last build on trusted.ci.jenkins.io, the (private) controller in charge of deploying this image, was the 6th of september, and its build logs mentions the https://github.com/jenkinsci/docker-inbound-agent/releases/tag/3046.v38db_38a_b_7a_86-1 release (3th of september).

=> it means that we have another systelm which is pushing this image. Searching in progress

cc @timja for info if it rings a bell (DockerHub?)

**Comment by dduportal** [comment]
At first sight, it's not the DockerHub "Automatic Builds" either:

![Capture d’écran 2022-09-23 à 16 53 29](https://user-images.githubusercontent.com/1522731/191989950-52901cea-f8a0-4dbd-a991-aa3b6051b3b2.png)
![Capture d’écran 2022-09-23 à 16 54 00](https://user-images.githubusercontent.com/1522731/191989957-4ed40a15-ac46-488c-9fce-053acab7b739.png)

**Comment by dduportal** [comment]
Triggered a rebuild of the main branch to make sure that the "latest" tags are overriden

**Comment by dduportal** [comment]
- A build of the latest tag has been triggered. It should also update the "latest" images. I'll close this issue once done and verified.
- PR https://github.com/jenkinsci/docker-inbound-agent/pull/280 to avoid this issue to happen again in the future.

**Comment by dduportal** [comment]
Closing as the "latest" image was re-updated:

```
docker pull jenkins/inbound-agent:jdk11
docker run --rm jenkins/inbound-agent:jdk11 -version
docker run --entrypoint bash -ti jenkins/inbound-agent:jdk11
jdk11: Pulling from jenkins/inbound-agent
1671565cc8df: Already exists 
27feb1ebfb33: Pull complete 
fdb9eb6bfcbb: Pull complete 
6383d5ee1f2c: Pull complete 
d72948d8e118: Pull complete 
0c4fee0d2207: Pull complete 
4f4fb700ef54: Pull complete 
12476606212c: Pull complete 
41a6861f3121: Pull complete 
Digest: sha256:e2a31ac60acc955aa85287e359d3240136bbcef7deb7fed15c73a121282481ce
Status: Downloaded newer image for jenkins/inbound-agent:jdk11
docker.io/jenkins/inbound-agent:jdk11
3046.v38db_38a_b_7a_86
jenkins@e0f1aff2d59a:~$ java -version
openjdk version "11.0.16.1" 2022-08-12
OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)
```
