### ISSUE TITLE
JDK8 Image bundles wrong agent jar version again. Regression from 276

### ISSUE THREAD

**Issue by cfraenkel** [jenkinsci/docker-inbound-agent#282]
### Jenkins and plugins versions report

<details>
Docker, JDK8 image  sha256:38e33ef80be2826094bd4aa01f8886a307e46c3f94a32a29d9f6ab6f2c7f6ae1

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

linux, but doesn't matter

### Reproduction steps

```bash
docker pull jenkins/inbound-agent:jdk8docker pull jenkins/inbound-agent:jdk8
docker run --rm  jenkins/inbound-agent:jdk8
```

### Expected Results

Container starts and lists help message (and can be used with kubernetes plugin etc.)

### Actual Results

Container fails to start because the bundled agent.jar requires a newer java runtime.
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: hudson/remoting/jnlp/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

### Anything else?

This is the same issue as in #276

**Comment by krachynski** [comment]
I'm running into this issue with `jenkins/inbound-agent:4.10-3-jdk8` which was pushed on October 18.

**Comment by krachynski** [comment]
Oops, it was pointed out that the latest 4.x release is actually 4.13.3-1-jdk8 (two months older). But even the most recent release is showing that the launcher in the image was compiled with Java 11

**Comment by dduportal** [comment]
Work in progress on the parent image (first) to fix this problem: https://github.com/jenkinsci/docker-agent/pull/299.

Once the parent image will have a valid release for JDK8, then inbound-agent will be updated as well.

**Comment by dduportal** [comment]
Hello @cfraenkel @krachynski , it should be fixed. The "last" version for JDK8 images has been released (https://github.com/jenkinsci/docker-inbound-agent/releases/tag/3028.va_a_436db_35078-2-jdk8, https://hub.docker.com/r/jenkins/inbound-agent/tags?page=1&name=3028.va_a_436db_35078-2 and https://hub.docker.com/r/jenkins/inbound-agent/tags?page=1&name=jdk8).

We also ensured that the "latest" image for JDK8 should be overriden.

Can you confirm by closing the issue (or commenting)?

**Comment by krachynski** [comment]
Started container ID 428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0 for node docker-agent-java8-000bsvg44yw5h from image: jenkins/inbound-agent:3028.va_a_436db_35078-1-jdk8
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): Error: A JNI error has occurred, please check your installation and try again
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 
Exception in thread "main"
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): java.lang.UnsupportedClassVersionError: hudson/remoting/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at java.lang.ClassLoader.defineClass1(Native Method)
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at java.security.AccessController.doPrivileged(Native Method)
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
Oct 31, 2022 3:49:41 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsvg44yw5h (428a03024404786034d6e3d28e52cf11f8608e1961fde3aca4615c6e7648f3e0): 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

**Comment by krachynski** [comment]
Started container ID b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91 for node docker-agent-java8-000bsxm7l0px3 from image: jenkins/inbound-agent:3028.va_a_436db_35078-2-jdk8
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): java.lang.UnsupportedClassVersionError: hudson/remoting/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): 	at java.lang.ClassLoader.defineClass1(Native Method)
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): 	at java.security.AccessController.doPrivileged(Native Method)
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
Oct 31, 2022 3:52:31 PM INFO io.jenkins.docker.client.DockerMultiplexedInputStream readInternal
stderr from docker-agent-java8-000bsxm7l0px3 (b64a8b2df4b5aa1dfd8c76ef36eb53c4ba31672a1383b808ada0fec02c9c9c91): 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
Oct 31, 2022 3:52:39 PM INFO hudson.slaves.NodeProvisioner update

**Comment by dduportal** [comment]
> I'm running into this issue with `jenkins/inbound-agent:4.10-3-jdk8` which was pushed on October 18.

@krachynski

Oh, I'm sorry I missed this message: you are using an old version of the remoting, while the "fixing" work was on the latest `https://github.com/jenkinsci/docker-inbound-agent/releases/tag/3028.va_a_436db_35078-2-jdk8`.

I'll see what I can do to fix the old versions, but you should upgrade to `jenkins/inbound-agent:3028.va_a_436db_35078-2-jdk8` as soon as possible.

**Comment by krachynski** [comment]
Sorry about that... I posted my comment before paying attention to the version number (this new version number sucks a lot). I deleted my comment and reposted the log from `jenkins/inbound-agent:3028.va_a_436db_35078-2-jdk8`

**Comment by dduportal** [comment]
> I just did a `docker image inspect` on the image I downloaded... the RepoDigests appears to match but the labels look interesting.... `"Version": "3028.va_a_436db_35078-3"` Wait. 3? I thought this was 2.

Long week-end for me and I messed up the comment here: the `-3` (third build)  is the correct one. I'm editing my comments.

**Comment by dduportal** [comment]
@krachynski good catch, thanks for sharing this: https://github.com/jenkinsci/docker-inbound-agent/blob/jdk8/8/debian/Dockerfile#L27 

=> It is not a functionnal problem (only image metadata) but it can clearly be improved.

**Comment by krachynski** [comment]
I guess, worst case, I could just use the Java 11 agent and add Java 8 to it as well.

My use case is that I need to compile some code that is currently incompatible with Java 9+ compiler. Once we get that fixed up, I won't need to bug y'all for a working JDK8 container.

**Comment by dduportal** [comment]
> I guess, worst case, I could just use the Java 11 agent and add Java 8 to it as well.
> 
> My use case is that I need to compile some code that is currently incompatible with Java 9+ compiler. Once we get that fixed up, I won't need to bug y'all for a working JDK8 container.

- It is fine for you to use `jenkins/inbound-agent:3028.va_a_436db_35078-2-jdk8`: there is only a Docker label minor issue which has no effect on the agent process.
 
- However, I recommend you to build your own image based on the JDK11 (to run the agent process with the same version as your Jenkins controller that should be JDK11 with last LTS) and adding a JDK8 with the `JAVA_HOME` version set in your build to this version. Something like this:

```Dockerfile
# https://hub.docker.com/layers/library/eclipse-temurin/8u345-b01-jdk/images/sha256-51211e4f5455d1b86ca456186749cee97e737f70dbdebf19981c7208e98999f2?context=explore
FROM eclipse-telurin:8u345-b01-jdk AS jdk8 

FROM jenkins/inbound-agent:3071.v7e9b_0dc08466-1-jdk11 AS final-image

ENV JAVA_HOME=/opt/java/openjdk8
COPY --from=jdk8 /opt/java/openjdk "${JAVA_HOME}"

# Ensure that agent uses JDK11
# https://github.com/jenkinsci/docker-inbound-agent/blob/jdk8/jenkins-agent#L90-L98
ENV JENKINS_JAVA_BIN /opt/java/openjdk
```

**Comment by krachynski** [comment]
For my particular use-case, I was able to follow with @dduportal's suggested Dockerfile to add Java 8 to a working Java 11 agent.

I think we're still seeing the wrong version of the agent inside the jdk8 image, but I'll leave it up to you to pursue further.

**Comment by dduportal** [comment]
As checked together:


- The "latest" JDK8 images should be used and are working as expected but ONLY if the Jenkins controller also uses a JDK8.
- The documentation at https://www.jenkins.io/doc/administration/requirements/java/ is not really clear that a Jenkins agent should always use the same major JDK (ideally the same JDK) as the controller. Call for contribution on this topic

**Comment by dduportal** [comment]
I'm closing the issue as it should be resolved. Feel free to re-open with details if you are still having issue with the JDK8 image.

**Comment by bvn13** [comment]
Have faced this issue with `jenkins/ssh-agent:latest-jdk8`

```
[01/04/23 20:59:05] [SSH] Starting agent process: cd "~" && java  -jar remoting.jar -workDir ~ -jar-cache ~/remoting/jarCache
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: hudson/remoting/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```
