### ISSUE TITLE
Please explain image versioning

### ISSUE THREAD

**Issue by artkrz** [jenkinsci/docker-inbound-agent#314]
### What feature do you want to see added?

I would like to see a clear info on how the image is versioned. It seams that last semantic version was release in September 2022 => https://github.com/jenkinsci/docker-inbound-agent/releases/tag/4.13.3-1 but now we get some other format? Can someone please explain what's going on? I would like to use latest stable realease.

**Comment by timja** [comment]
This image follows the remoting projects versioning, and then adds a build number to the end. 

It does not use semantic versioning.

`${REMOTING_VERSION}-${BUILD_NUMBER}`

there's a bit more information here: https://www.jenkins.io/doc/developer/publishing/releasing-cd/

**Comment by artkrz** [comment]
@timja do I understand correctly this is only format now and there's no "stable" release, just continues versions?

**Comment by artkrz** [comment]
Also, looks like last tag pushed to docker hub is `3046.v38db_38a_b_7a_86-1-jdk11`

- https://github.com/jenkinsci/docker-inbound-agent/releases/tag/3046.v38db_38a_b_7a_86-1
- https://hub.docker.com/layers/jenkins/jnlp-slave/3046.v38db_38a_b_7a_86-1-jdk11/images/sha256-302dd693f7f10f825495ab480f3a009971760809eca5075095eb5e9cdad89e1d

WIll ne version be pushed at some point?

**Comment by dduportal** [comment]
@artkrz the image `jenkins/jnlp-slave` in deprecated (as per the first admonition in the readme in https://hub.docker.com/r/jenkins/jnlp-slave) in favor of `jenkins/inbound-agent` (https://hub.docker.com/r/jenkins/inbound-agent).

**Comment by artkrz** [comment]
Thanks. Missed that, sorry. Can You confirm that `3077.vd69cf116da_6f-3` is the new and only format now?

**Comment by dduportal** [comment]
> @timja do I understand correctly this is the only format now and there's no "stable" release, just continues versions?

That is correct. You should pin a given version in your system and update this version after testing it. Because the concept of "stable" is vague and hard to scale to all the use cases without requiring effort by people helping to maintain.

**Comment by dduportal** [comment]
> Thanks. Missed that, sorry. Can You confirm that `3077.vd69cf116da_6f-3` is the new and only format now?

For now yes. Any change on the version pattern would be discussed (and I really hope) communicated through at least a blog post on jenkins.io :) 

If you need some "safety", the whole Jenkins Infrastructure also relies on this pattern;: any changhe would require a bit of rework :) (you can also check what we do to keep our image up to date if you are interested)
