### ISSUE TITLE
Docker image for docker-inbound-agent from debian bullseye distribution based agent docker image

### ISSUE THREAD

**Issue by rekathiru** [jenkinsci/docker-inbound-agent#452]
### What feature do you want to see added?

Currently, as there is no debian-bullseye distribution based docker image available for inbound agent in https://hub.docker.com/r/jenkins/inbound-agent/tags?page=1, I couldn't build docker images either from inbound-agent/jdk11 or inbound-agent/latest-jdk11 in FIPS enabled Kubernetes Clusters as the Dockerfile executing `apt-get update` to install some additional packages on top of base inbound-agent. `apt-get update` is not working in FIPS enabled Kubernetes clusters according to https://github.com/debuerreotype/docker-debian-artifacts/issues/202. The workaround/solution is to use debian bullseye distribution.

Sample Dockerfile that is not working:

```
FROM jenkins/inbound-agent:jdk17

USER root

RUN apt-get update && \
        apt-get install curl make
```

Since the jenkins/agent is already providing `bullseye` related docker tags as in [here](https://hub.docker.com/r/jenkins/agent/tags?page=1&name=bullseye), can we take over the bullseye related base agent image and publish bullseye versions for inbound-agent as well? This will unblock rebuilding inbound agent image in FIPS enabled Kubernetes Clusters.

**Comment by timja** [comment]
Debian maintainers has pretty clearly expressed that they are not FIPS certified and do not test for it at all:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014517#37

We are only using bookworm now for debian and do not plan to maintain old distributions
You are welcome to build your own FIPS certified image or try a different distribution
