### ISSUE TITLE
Handling the setting /var/run/docker.sock container mount point

### ISSUE THREAD

**Issue by citizenkahn** [jenkinsci/docker-inbound-agent#92]
How do you handle the situation where I want my jenkins container to be capable of running docker on the ecs.  for example this case:

```
node('aws-ecs-node') {
    def dockerRegistry="https://myregistry.me.com/"
    def dockerRegistryCredId="artifactoryjenkins"
    def dockerImage="myimage:latest"
    
    println "on jenkins node"
    sh "id"
    sh "ls -l /var/run/docker.sock"
    docker.withRegistry(dockerRegistry, dockerRegistryCredId) {
		docker.image(dockerImage).inside('-u root') {
            println "in ${dockerImage}"
            sh "id"
            sh "ls -l /var/run/docker.sock"
		}
    }
    
}
```

If when I build the image linked to `aws-ecs-node` I hard code the docker GID from the EC2 instances serving the ECS cluster is all works.

However,  when I upgrade ECS docker GID can change leading to lack of access to docker.sock.

It seems from reading other issues etc that pushing the detection of GID, group creation and adding jenkins to that group could be done within the jenkins start up script

Pseudo code:
1. if /var/run/docker.sock exists and it has a gid
1. if that gid doesn't exist create as docker group
1. if docker group exists as another gid - fail
1. add jenkins user to that group

Or we could create a random hash name for group and always add

**Comment by dduportal** [comment]
Docker on Docker (e.g. socket mounting) and Docker in Docker (nested containers) are not recommended: https://github.com/jenkinsci/docker-inbound-agent/issues/223#issuecomment-1712005925.

In the particular case of ECS, it is to be avoided as the containers won't be tracked properly.


Anyway, the angle would be to build your own agent container image on top of this one and to provide a custom entrypoint which role would be to check the UID and GID of the socket at runtime, then update the UID/GID of the `jenkins` user in the image, and then proceed to execute the current entrypoint as `jenkins` user.
